<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/admin/js/materialize.min.js"></script>
<script>$(document).ready(function () {
        // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
        $('.modal-trigger').leanModal();
        $('select').material_select();
    });</script>
</body>
</html>